// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelExecution() {
  return window['go']['processing']['FrontendApp']['CancelExecution']();
}

export function CheckIfResultsExist() {
  return window['go']['processing']['FrontendApp']['CheckIfResultsExist']();
}

export function FullReset() {
  return window['go']['processing']['FrontendApp']['FullReset']();
}

export function GetResults() {
  return window['go']['processing']['FrontendApp']['GetResults']();
}

export function RevealInExplorer(arg1) {
  return window['go']['processing']['FrontendApp']['RevealInExplorer'](arg1);
}

export function SelectFolder() {
  return window['go']['processing']['FrontendApp']['SelectFolder']();
}

export function ShowResults() {
  return window['go']['processing']['FrontendApp']['ShowResults']();
}

export function StartExecution(arg1) {
  return window['go']['processing']['FrontendApp']['StartExecution'](arg1);
}
