// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LogDetailedStatus(arg1) {
  return window['go']['processing']['FrontendApp']['LogDetailedStatus'](arg1);
}

export function LogProgress(arg1, arg2) {
  return window['go']['processing']['FrontendApp']['LogProgress'](arg1, arg2);
}

export function SelectFolder() {
  return window['go']['processing']['FrontendApp']['SelectFolder']();
}

export function ShowResults() {
  return window['go']['processing']['FrontendApp']['ShowResults']();
}

export function StartExecution(arg1) {
  return window['go']['processing']['FrontendApp']['StartExecution'](arg1);
}
