// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function SelectFolder():Promise<string>;

export function ShowResults():Promise<void>;

export function StartExecution(arg1:models.ExecutionParams):Promise<void>;
